# Generated by Django 2.0 on 2018-03-09 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PCW_APP', '0003_profile_qr_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Markers',
        ),
        migrations.AddField(
            model_name='events',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='events',
            name='lng',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
    ]
