# Generated by Django 2.0 on 2018-03-05 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PCW_APP', '0003_profile_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Organization',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='signed_in',
            field=models.BooleanField(default=False),
        ),
    ]
