# Generated by Django 2.0 on 2018-03-09 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PCW_APP', '0004_auto_20180309_0330'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignInTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.DateTimeField(blank=True, null=True)),
                ('endTime', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
