# Generated by Django 2.0 on 2018-03-08 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PCW_APP', '0004_auto_20180305_0712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Organization',
        ),
    ]
