# Generated by Django 2.0.2 on 2018-03-09 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PCW_APP', '0005_signintime'),
        ('PCW_APP', '0006_profile_organization'),
    ]

    operations = [
    ]
