# Generated by Django 2.0.1 on 2018-04-04 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PCW_APP', '0008_auto_20180403_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='location',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
